### PR TITLE
fix(input): replace onKeyPress flow type to SyntheticKeyboardEvent

### PR DESCRIPTION
**Pull request by fanglansheng**
#### Description

Replaced <Input/> component onKeyPress, onKeyUp, onKeyDown flow type to KeyboardEvent.
#### Scope

- [x] Patch: Bug Fix
- [ ] Minor: New Feature
- [x] Major: Breaking Change

### CODE REVIEW

**Comment by fanglansheng** [comment]
@gergelyke I don't think I have the access to assign reviewers or add tags, can you help me out here? Thanks!

**Comment by chasestarr** [comment]
thanks for putting up the pr!

**Comment by gergelyke** [comment]
@fanglansheng would you mind resolving the merge conflict? after that, I believe we are good to land it - thanks again for the contribution!

**Comment by fanglansheng** [comment]
Tried to merge but getting errors:
```
Commit failed - exit code 1 received, with output: '/Users/chuanz/Documents/baseui/node_modules/husky/lib/runner/bin.js:3
const _1 = require("./");
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3'
```
This error also happened after I sync the upstream/master to my forked repo and do `git push`

**Comment by chasestarr** [comment]
^^ that error may be related to node version. try using LTS. it looks like the conflict should be resolved by deleting the `src/input/README.md`. we deleted the readme files for each component.

**Comment by gergelyke** [comment]
@fanglansheng just wanted to gently bump this - can you help us resolve this merge conflict so we can land it?

**Comment by chasestarr** [comment]
thanks for putting the pr up @fanglansheng 

i pushed the change to base ui here https://github.com/uber-web/baseui/pull/950

**Pull request closed without merging**
