### PR TITLE
style(theme): update large breakpoint

### PR DESCRIPTION
**Pull request by chrisrauh**
#### Description

Update the large breakpoint value to match the latest base web design spec.

#### Scope

- [x] Patch: Bug Fix
- [ ] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

**Comment by gergelyke** [comment]
should we release this as part of https://github.com/uber-web/baseui/pull/1697?

**Comment by sandgraham** [comment]
Yeah - @chrisrauh, mind if we put this in our `v9` which has a lot of style updates. This might be breaking for some folks.

**Comment by gergelyke** [comment]
I've just changed the base to be against the v9 branch

**Comment by chrisrauh** [comment]
> Yeah - @chrisrauh, mind if we put this in our `v9` which has a lot of style updates? This might be breaking for some folks.

That's fine if it's not a long delay, we are also anxiously waiting for those other ones to land. :-)

**Pull request merged**
