### PR TITLE
feat(datepicker): positive, error and disabled states

### LINKED ISSUE #1468: [TimezonePicker] Does not support `error` or `positive` property
## Current Behavior

Most input fields have the `error` and `positive` which changes the design of the fields. The `TimezonePicker` seems to lack this feature.

## Expected Behavior

Setting `error` or `positive` will change the field state/design accordingly.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v7.8.0  |
| React   |   16.8.6      |
| browser |     Chrome 75.x    |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

### LINKED ISSUE #1469: [TimePicker] Does not support `error` or `positive` property
## Current Behavior

Most input fields have the `error` and `positive` which changes the design of the fields. The `TimePicker` seems to lack this feature. Related to #1468 

## Expected Behavior

Setting `error` or `positive` will change the field state/design accordingly.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v7.8.0  |
| React   |   16.8.6      |
| browser |     Chrome 75.x    |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by qqingvarqq**
Resolves #1469, Resolves #1468 

#### Description
Added positive, error, disabled states(https://baseweb.design/components/input/#input-with-all-available-states)  to TimePicker and TimezonePicker Components.
Removed redundant check for `selectProps && selectProps.overrides` since `selectProps` is always object.
Added positive state to the DatePicker component.

#### Scope

- [ ] Patch: Bug Fix
- [X] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

**Comment by gergelyke** [comment]
thank you again for the contribution @qqingvarqq !

**Comment by chasestarr** [comment]
thank you - do you mind adding a `datepickers-color-states.scenario.js` file so that we can have it run visual regression tests?

**Comment by qqingvarqq** [comment]
Ok, I'll also add examples to the documentation site too

**Comment by qqingvarqq** [comment]
Updated, but for some reason, I can't pull changes to this Pr (new commit exist in origin `qqingvarqq:pickers-enhancement`) probably it can do only code owners after review.

**Comment by chasestarr** [comment]
I believe if you fetch and merge in changes from the this repo's master it will work. You can also force push to your own branch if needed

**Comment by qqingvarqq** [comment]
changes are available for review

**Comment by gergelyke** [comment]
Thanks for the contribution @qqingvarqq ! 🤗

**Pull request merged**
