### PR TITLE
feat(rtl): enable rtl layout for components

### LINKED ISSUE #1669: [RTL] Button enhancers
To reproduce, open the dev tools, and run `document.dir = 'rtl'`

AC:

* the component should have the same spacings and structure in `rtl` too.

Screen Shot 2019-08-01 at 11 13 46 AM
Screen Shot 2019-08-01 at 11 13 38 AM

### PR DESCRIPTION
**Pull request by jh3y**
#### Description
Resolves #1669 #1676 #1680 #1671 #1677 #1679 #1672 #1673 #1678 

⚠️ Be mindful that in some storybook scenarios, you need to explicitly set `dir="rtl"` on the containing `iframe` `html` tag. Otherwise, you won't see `rtl` in effect. This is true with scenarios such as that for `modal`.

#### Scope

- [ ] Patch: Bug Fix
- [x] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

**Comment by gergelyke** [comment]
@jh3y can we close the rest of the PRs re RTL?

**Comment by jh3y** [comment]
Yes. I just didn't want to in case this one wasn't right.

**Comment by gergelyke** [comment]
looks great! few minor comments:

* once the dnd is grabbed, it jumps back to ltr
* for the menu, can you change to example to include nested menus?

**Comment by jh3y** [comment]
> once the dnd is grabbed, it jumps back to ltr

It will do because the actual `document.dir` hasn't been set to `rtl` and it's being rendered in a portal.

I will add the nested version for menu.

**Comment by gergelyke** [comment]
> > once the dnd is grabbed, it jumps back to ltr
> 
> It will do because the actual `document.dir` hasn't been set to `rtl` and it's being rendered in a portal.
> 
> I will add the nested version for menu.

sounds great, thank you

one last thing - could you also add direction switcher to the doc site (and fix any issues that look odd), something like material-ui has in a follow-up pr?

**Comment by jh3y** [comment]
I can't promise that being a short task. Do you have an icon or design for this?

**Comment by gergelyke** [comment]
> I can't promise that being a short task. Do you have an icon or design for this?

Probably we could use something like this https://www.iconfinder.com/icons/103727/align_right_text_icon

**Comment by gergelyke** [comment]
It seems like in a few cases the LTR versions changed too - can you take a look at these ones?

Screen Shot 2019-08-07 at 11 20 30 AM
Screen Shot 2019-08-07 at 11 20 26 AM

**Comment by gergelyke** [comment]
One last thing - it seems like the pagination changed a bit too

Screen Shot 2019-08-08 at 9 29 26 AM

**Pull request merged**
