### PR TITLE
fix(accordion-panel): use background-color instead of background

### PR DESCRIPTION
**Pull request by MythlinMasterdo**
#### Description

- Use `background-color` instead of `background` in accordion-panel Header to avoid React warnings when setting `background-color` via overrides. `background` should only be used in conjunction with multiple `background` properties but in this case, we are only setting color so we should use `background-color` similar to what we do on line 73 for the content styles. 

#### Scope

- [X] Patch: Bug Fix

### CODE REVIEW

**Comment by gergelyke** [comment]
thank you @MythlinMasterdo !

**Comment by gergelyke** [comment]
@MythlinMasterdo can you update the snapshot tests please? they seem to be failing

**Comment by MythlinMasterdo** [comment]
@gergelyke Sure no problem

**Comment by gergelyke** [comment]
closing this in favor of https://github.com/uber-web/baseui/pull/1873

**Pull request closed without merging**
