### PR TITLE
feat: Slider label overlap

### LINKED ISSUE #1159: [Slider] Handle labels overlap if too close together
## Current Behavior

Image Pasted at 2019-4-15 17-15

## Expected Behavior

I would expect that the labels change position to avoid overlapping

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v6.13.0  |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by jh3y**
#### Description
- Fixes #1159 

updated-range

#### Scope

- [ ] Patch: Bug Fix
- [x] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

**Comment by jh3y** [comment]
Are you able to provide some pointers on how to overcome those `flow` issues. I'm not 100% sure on what needs to be added in there to make it happy.

**Comment by tajo** [comment]
> Are you able to provide some pointers on how to overcome those `flow` issues. I'm not 100% sure on what needs to be added in there to make it happy.

I think you need to update react-range's flow types (like the missing useThumbOverlap export). It's written in TypeScript, so flow types are maintained manually.

**Comment by jh3y** [comment]
This did go into the `react-range` PR https://github.com/tajo/react-range/blob/master/flowtypes/utils.js.flow#L11

Also, `flow` is complaining about the `RefObject` on `React` and `$min` and `$max` on lines I haven't changed 😕

**Comment by tajo** [comment]
> This did go into the `react-range` PR https://github.com/tajo/react-range/blob/master/flowtypes/utils.js.flow#L11

You also need to export it here: https://github.com/tajo/react-range/blob/master/flowtypes/index.js.flow#L6

> Also, `flow` is complaining about the `RefObject` on `React`

Maybe this instead? 

```
rangeRef = React.createRef<Range>();
```

> and `$min` and `$max` on lines I haven't changed 😕

Not sure about this one, hm.

**Comment by chasestarr** [comment]
i'm going to look at this locally

**Comment by jh3y** [comment]
Although this has been updated so the `react-range` flow checks pass. I'm still getting issues with `$min`, `$max` and `React.RefObject`. Any ideas @tajo?

I see the linting is complaining also about the option for `weak-types`?

**Comment by tajo** [comment]
> Although this has been updated so the `react-range` flow checks pass. I'm still getting issues with `$min`, `$max` and `React.RefObject`. Any ideas @tajo?
> 
> I see the linting is complaining also about the option for `weak-types`?

It seems we lost typing for `styled` props in general

Screen Shot 2019-07-29 at 3 50 18 PM

Not sure why it's not throwing in other places, but you can use `//$FlowFixMe` for now and ask @chasestarr for help the next week?

`React.RefObject` doesn't exist. It should be typed as `ref = createRef<TYPE>()`

However, it seems there are also some inconsistencies with `HTMLElement | null` vs `Range | null`, some casting might be needed? Should `useThumbOverlap` be able to deal with `null`?

**Comment by jh3y** [comment]
Opened a PR on `react-range` for the additional `flow` changes. Will use `$FlowFixMe` in `slider.js` 👍

**Comment by jh3y** [comment]
@tajo Updated and passing `flow` etc. locally. However, `yarn lint` complains about `flowtype/no-weak-types` having the wrong value. Fixing this reveals a bundle of linting errors around missing `display` name etc.

**Pull request merged**
