### PR TITLE
chore(language) - Fix inconsistent boolean props

### PR DESCRIPTION
**Pull request by IgorWilbert**
For #1109

#### Description

Changes isLoading to loading in: select, button, table, pagination
Changes isSelected to selected in: button, button-group, datepicker, dnd-list, pagination, rating
Changes isIndeterminate to determinate in: checkbox
Changes isHovered to hovered in: checkbox, datepicker, radio,tag

#### Scope

- [X] Patch: Bug Fix
- [ ] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

**Comment by IgorWilbert** [comment]
Hello! Instead of making consistency checks for each component, I changed all occurrences across the whole project, because I thought it would be favourable for future consistency. E. g. if we decide to make a new component with both subcomponents `checkbox` and `radio, and `checkbox` uses `isHovered` while `radio` uses `hovered`, we would still have the same problem.

**Comment by gergelyke** [comment]
hi Igor! to me it seems like a huge breaking change, with minor benefits - I'd either leave things as is, or make sure we support both prop names

what do you all think @chasestarr @nadiia @tajo @sandgraham ?

**Comment by chasestarr** [comment]
I'd personally rather not make this change right now since there will be many other breaking changes in the v7 release. we generally want to make the upgrade process as painless as possible. maybe this change can be saved for a later date?

**Comment by gergelyke** [comment]
I think that makes perfect sense

**Comment by gergelyke** [comment]
closing this for now, let's revisit later

**Pull request closed without merging**
