### PR TITLE
fix(typescript): custom theme type support

### PR DESCRIPTION
**Pull request by alexzywiak**
#### Description

Allow typescript to use custom theme types when using the `createTheme` and `styled` functions.

#### Scope

- [x] Patch: Bug Fix
- [ ] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

**Comment by alexzywiak** [comment]
Two questions:

Previously there was a typescript type definition test file, but I was unable to find it.  I am happy to write tests if you point me in the right direction.  

Should I expand the custom theme typing to other files that hardcode the baseui theme type such as `WithStyleFn` or `BaseProvider`?

**Comment by tajo** [comment]
> Previously there was a typescript type definition test file, but I was unable to find it. I am happy to write tests if you point me in the right direction.

Yea, that was deleted when we moved typings to this repo. Our primary way of testing TS types is through examples `./documentation-site/examples/*/**.tsx`.

> Should I expand the custom theme typing to other files that hardcode the baseui theme type such as WithStyleFn or BaseProvider?

That would be nice. Although, we tend to not use `styled` and `withStyle` helpers anymore and prefer `useStyletron` API instead. So for the start, I would prefer an addition of `createUseStyletron` that would let you to pass the custom theme type. I'm surprised we don't have this function already (so the implementation in flow + its TS typedefs should be added).

**Comment by alexzywiak** [comment]
@tajo `createThemedUseStyletron<CustomThemeType>()` works as expected already.  Didn't see that you have recommended to move away from `styled` in favor of `useStyletron`.  I'll start doing that, too.  

I updated `WithStyleFn` for completeness and updated the types in the documentation site example.

**Comment by gergelyke** [comment]
@alexzywiak can you help us resolve the merge conflicts?

**Comment by alexzywiak** [comment]
@gergelyke Fixed merge conflicts

**Comment by gergelyke** [comment]
thank you @alexzywiak !

**Pull request merged**
