### PR TITLE
fix(accordion): update focus highlight

### LINKED ISSUE #1323: Accordion UI Bug
## Blue border highlighted when open, but when back to being closed, bottom blue border is hidden while the left, right and top borders remain highlighted in blue.
Shouldn't they all be deselected when the accordion closes? 

uberaccordionuibug

## Your Environment

I tested this on the Base UI website, accordion section.

| Tech    | Version |
| ------- | ------- |
| Base UI | v?.?.?  |
| React   |         |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by qqingvarqq**
Fixes #1323 

#### Description

Removed position relative because it changes stacking, which causes to hiding focus highlight at the bottom, as described in the linked issue.

This fix also fixes inconsistent with 'outlining content', when we add overrides, because `outline: 2px solid #F6BA8B;` is outside box model that's mean that we should show full outlining or hide them completely. 
(It's from the documentation site https://baseweb.design/components/accordion/#overrides)
Before:
before

After:
after

If you need to hide all content even outside the box-model I can make appropriate changes for that.
#### Scope

- [x] Patch: Bug Fix

### CODE REVIEW

**Comment by gergelyke** [comment]
it seems like it introduces a visual regression in one of the table examples

Screen Shot 2019-06-14 at 1 58 06 PM

can you please take a look at that?

**Comment by qqingvarqq** [comment]
Sure
The plus icon moved to the left because previously it was hard coded by `position absolute` and `left: 12px`, and now there is no `position relative` in the parent.
I changed CSS in this table so the plus icon is no longer hardcoded.
I'm new in this project so if something wrong, I can make appropriate changes to this PR

**Comment by qqingvarqq** [comment]
@gergelyke Thank you for your time. I see that screener check failed again can you provide where regression coming because I check storybook and it seems that stories don't have regression. Maybe I miss something?

**Comment by chasestarr** [comment]
it's specifically when running IE 11

**Comment by qqingvarqq** [comment]
I looked at these changes when running IE 11. (`table-cells` page)
Master Branch (IE):
master
My branch (fix-accordion-ui) (IE):
fix-ui

Actually, those changes are good, because
1. fixed vertical centering of plus icon under ie,
2. The 'Expandable' column is not overlapping 'Amount' column, under ie
==============
Last one change
3. 'Expanded' column has a normal width under ie
So waiting for feedback

**Comment by gergelyke** [comment]
> I looked at these changes when running IE 11. (`table-cells` page)
> Master Branch (IE):
> master
> My branch (fix-accordion-ui) (IE):
> fix-ui
> 
> Actually, those changes are good, because
> 
> 1. fixed vertical centering of plus icon under ie,
> 2. The 'Expandable' column is not overlapping 'Amount' column, under ie
>    ==============
>    Last one change
> 3. 'Expanded' column has a normal width under ie
>    So waiting for feedback

oh, that makes perfect sense, thanks for the fix! I've just started running the CI on it 🤞

**Comment by qqingvarqq** [comment]
It's very strange that build was failed. 
There are no changes to Slack link, and Slack link is working.
├─BROKEN─ https://join.slack.com/t/baseui/shared_invite/enQtNDI0NTgwMjU0NDUyLTk3YzM1NWY2MjY3NTVjNjk3NzY1MTE5OTI4Y2Q2ZmVkMTUyNDc1MTcwYjZhYjlhOWQ2M2NjOWJkZmQyNjFlYTA (ERRNO_ECONNREFUSED)

**Comment by gergelyke** [comment]
thanks for the contribution @qqingvarqq 👏

**Pull request merged**
