### PR TITLE
feat(select): add single and multi select as separate components

### PR DESCRIPTION
**Pull request by nadiia**

### CODE REVIEW

**Comment by gergelyke** [comment]
I like that you didn't add this to the documentation site - it will enable to incorporate some of the ideas from https://github.com/uber-web/baseui/issues/1821 into it, without a breaking change 👍

**Comment by nadiia** [comment]
> do we want to include this

Not into the scope of this PR.

**Comment by chasestarr** [comment]
Does not being on the docs site indicate api changes are non-breaking? I considered shipping the `PhoneInputLite` component as unstable so that we could have more flexibility in the short-term to fix any issues.

**Comment by nadiia** [comment]
> Does not being on the docs site indicate api changes are non-breaking? I considered shipping the `PhoneInputLite` component as unstable so that we could have more flexibility in the short-term to fix any issues.

Not really, also considering the single select reused and available for overrides in the phone input component.

**Pull request merged**
