### PR TITLE
feat: input rtl support

### LINKED ISSUE #1671: [RTL] Input
To reproduce, open the dev tools, and run `document.dir = 'rtl'`

AC:

* the component should have the same spacings and structure in `rtl` too.

Screen Shot 2019-08-01 at 11 21 38 AM
Screen Shot 2019-08-01 at 11 21 33 AM
Screen Shot 2019-08-01 at 11 22 13 AM
Screen Shot 2019-08-01 at 11 22 06 AM

### PR DESCRIPTION
**Pull request by jh3y**
Resolves #1671 

#### Scope

- [ ] Patch: Bug Fix
- [x] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

**Comment by gergelyke** [comment]
it seems like the enhancer's padding needs some change too? in rtl, it seems like it should has more spacing

Screen Shot 2019-08-06 at 10 15 24 AM
Screen Shot 2019-08-06 at 10 14 39 AM

**Comment by jh3y** [comment]
This is part of the `Button` code therefore it's updated in the PR related to enhancers.

**Comment by gergelyke** [comment]
> This is part of the `Button` code therefore it's updated in the PR related to enhancers.

👍

**Comment by jh3y** [comment]
Ahh actually it isn't part of the `Button` code. The enhancers are inline coded. But as we are now reusing the scenario the padding is that for `ltr`. Prior to this I was setting the appropriate padding in the `rtl` scenario. It's down to the user and the way they implement the enhancers.

**Pull request closed without merging**
