### PR TITLE
fix(input): change onInputChange event to be type input

### PR DESCRIPTION
**Pull request by jonsadka**
Referencing `e.target.value` throws flow error `Cannot get e.target.value because property value is missing in EventTarget [1].`.  Input type should be updated to `SyntheticInputEvent`

### CODE REVIEW

**Comment by jonsadka** [comment]
Any idea why `buildkite/baseui/saucelabs-selenium` is failing? I don't have access

**Comment by chasestarr** [comment]
looks like one of the clean-up processes timed out. just re-ran to see how it goes

```

1) The button component "after all" hook:
--
  | Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  | at Timeout.<anonymous> (node_modules/mocha-nightwatch/lib/runnable.js:232:19)

```

**Comment by jonsadka** [comment]
Awesome, thanks yall

**Comment by chasestarr** [comment]
thanks for sending the pr @jonsadka

**Pull request merged**
