### PR TITLE
feat(border-radius): removes radius from components

### PR DESCRIPTION
**Pull request by chasestarr**
removes border-radius from the following components:

- card
- file-uploader
- modal
- popover
- toast
- tooltip

### CODE REVIEW

**Comment by kaushalyap** [comment]
@chasestarr @gergelyke May I ask why you guys removed border radius? Any way to use it in current version?.

**Comment by sandgraham** [comment]
@kaushalyap

Info on rounded corner changes: https://baseweb.design/blog/base-web-v7/#rounded-corners

You can also customize border radius scale (ex: `theme.borders.radius100`): https://baseweb.design/guides/theming/#borders

As to why the changes happen, Base Web is part of Uber's design system. As the brand evolves, so too does the design system.

**Comment by kaushalyap** [comment]
@sandgraham  Thanks

**Pull request merged**
