### PR TITLE
feat(data-table): Improve categorical filter ui

### PR DESCRIPTION
**Pull request by chasestarr**
#### Description

Screen Shot 2019-09-12 at 3 10 48 PM

Screen Shot 2019-09-12 at 6 11 08 PM

#### Scope
- [x] Minor: New Feature

### CODE REVIEW

**Comment by tajo** [comment]
Not specific to this PR but it seems that the dark mode should have better contrast?

Screen Shot 2019-09-18 at 10 38 58 AM

**Comment by tajo** [comment]
Could you update the docs site for easier testing?

**Comment by chasestarr** [comment]
> Not specific to this PR but it seems that the dark mode should have better contrast?

Yeah, haven't gotten around to dark mode yet.

> Could you update the docs site for easier testing?

I could add specific examples listing the uber vehicles. Is that what you're thinking about?

**Comment by tajo** [comment]
> I could add specific examples listing the uber vehicles. Is that what you're thinking about?

Oh, I wanted to test/see the search functionality. I guess it's not just enabled?

**Comment by chasestarr** [comment]
> > I could add specific examples listing the uber vehicles. Is that what you're thinking about?
> 
> Oh, I wanted to test/see the search functionality. I guess it's not just enabled?

ah right, there needs to be 10 items. i'll update the example for that

**Comment by chasestarr** [comment]
updated to include more options in the example

Screen Shot 2019-09-19 at 12 51 37 PM

**Comment by gergelyke** [comment]
When the filter UI is open, should we move focus inside the popover? I couldn't Tab into the filter UI

**Comment by chasestarr** [comment]
> When the filter UI is open, should we move focus inside the popover? I couldn't Tab into the filter UI

I added this feature in the numerical filter pr!

**Pull request merged**
