### PR TITLE
Correct the name of the project

### PR DESCRIPTION
**Pull request by oliviertassinari**
#### Description

Welcome to the club :)

#### Scope

- [x] Patch: Bug Fix
- [ ] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

**Comment by gergelyke** [comment]
thanks @oliviertassinari 🤗

**Comment by oliviertassinari** [comment]
I love the customization playground: 

image

**Comment by gergelyke** [comment]
thank you! is there anything you miss from the documentation site?

**Comment by oliviertassinari** [comment]
I'm not sure. I haven't looked enough to tell.

**Pull request merged**
