### PR TITLE
chore(side-navigation): rename subnav -> subNav and sidenav -> side-nav

### PR DESCRIPTION
**Pull request by leyanlo**
#### Description

rename subnav -> subNav and sidenav -> side-nav for consistency

#### Scope

- [ ] Patch: Bug Fix
- [ ] Minor: New Feature
- [x] Major: Breaking Change

### CODE REVIEW

**Comment by chasestarr** [comment]
thanks @leyanlo. going to keep this pr open until the next major

**Comment by nadiia** [comment]
Thanks for the PR, @leyanlo! Could you add a migration guide for the change? You can find an example of it [here](https://github.com/uber-web/baseui/blob/master/docs/migrations/00868.md)

**Comment by leyanlo** [comment]
Updated with migration guide. Let me know if it looks ok!

**Comment by gergelyke** [comment]
Looks great! Can you open this PR against the `v7` branch please?

**Comment by leyanlo** [comment]
Updated PR against `v7` branch

**Pull request merged**
