### PR TITLE
feat(flex-grid): add flex-grid component

### LINKED ISSUE #1237: Grid system
Hallo, do you have any plans to have a [grid system](https://ant.design/components/grid/)?

### PR DESCRIPTION
**Pull request by leyanlo**
#### Description

Introduce FlexGrid utility component, which provides a CSS grid-like experience, built on flexbox, for applications that need to support customers on Internet Explorer.

Also
* export ResponsiveT and ScaleT types from Block
* add react-is dependency needed to flatten fragments
* add flattenFragments() in react-helpers.js
* add responsive-helpers.js and use in Block
* add string.js helper with camelToKebab method
* add flex-grid documentation with examples

Maybe fixes #1237, though it’s more of a utility component for those who can’t use CSS grid.

#### Scope

- [ ] Patch: Bug Fix
- [x] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

**Comment by gergelyke** [comment]
thank you Leyan! Would you mind adding visual regression tests instead of the snapshots? you can find examples by checking out a `.scenario.js` file in any of the test directories.

**Comment by tajo** [comment]
Nice work!

Are all these [APIs](https://deploy-preview-1289--baseui.netlify.com/components/flex-grid/#flexgrid-unequal-widths) really supported? If so, why not to use `gridColumn` to implement this [example](https://deploy-preview-1289--baseui.netlify.com/components/flex-grid/#flexgrid-unequal-widths) rather than doing some math manually?

**Comment by nadiia** [comment]
🎆 Looks great!

**Comment by leyanlo** [comment]
> thank you Leyan! Would you mind adding visual regression tests instead of the snapshots? you can find examples by checking out a `.scenario.js` file in any of the test directories.

@gergelyke Added scenarios by copying over from the documentation examples. Is this ok? Also would like to keep a few snapshots to make sure prop behavior is ok.

> Nice work!
> 
> Are all these [APIs](https://deploy-preview-1289--baseui.netlify.com/components/flex-grid/#flexgrid-unequal-widths) really supported? If so, why not to use `gridColumn` to implement this [example](https://deploy-preview-1289--baseui.netlify.com/components/flex-grid/#flexgrid-unequal-widths) rather than doing some math manually?

@tajo Yes, all the Block APIs are supported. The issue with `gridColumn` is the limited support in IE. Rather than removing certain props from the Block API for FlexGrid, I decided to pass them all in for simplicity, and leave it up to the user to do what they will. I’ve reordered the prop types so the three FlexGrid props are first, so hopefully that clears things up:
https://deploy-preview-1289--baseui.netlify.com/components/flex-grid/

> 🎆 Looks great!

@nadiia Thanks!

**Comment by 201Factory** [comment]
Thx that's usefull

**Pull request merged**
