### PR TITLE
fix(popover): fix type definition

### PR DESCRIPTION
**Pull request by bwolfe-celartem**
Relates to https://github.com/uber-web/baseui/issues/1152

#### Description

Adds popperOptions to popover type defintions, was somehow missed back in June.

#### Scope

- [X] Patch: Bug Fix
- [ ] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

**Comment by gergelyke** [comment]
thanks @bwolfe-celartem 🤗

**Comment by bwolfe-celartem** [comment]
CLA Assistant is quite laggy at the moment, I'll have it signed shortly.

**Comment by bwolfe-celartem** [comment]
Okay that's signed, you can re-run the Greetings check if you need!

**Comment by gergelyke** [comment]
> Okay that's signed, you can re-run the Greetings check if you need!

I am not sure why it's failing - but it's not crucial to land this pr. Will look into that

**Comment by gergelyke** [comment]
thanks for the contribution @bwolfe-celartem - we'll cut a release later today

**Pull request merged**
