### PR TITLE
docs(example): add readme docs

### PR DESCRIPTION
**Pull request by gergelyke**

### CODE REVIEW

**Comment by kahwee** [comment]
You can do this instead:

```
  .addDecorator(withInfo)
  .add('Controlled and uncontrolled input', () => <ControlledInput />, {
    info: Readme,
  })
```

You're using the previous storybook addon pattern.

**Comment by gergelyke** [comment]
yeah, this wont work sadly - for this we have to wait for version 4 (it is in alpha now)

**Comment by gergelyke** [comment]
generally speaking, what do you think about the idea?

**Comment by kahwee** [comment]
I'm assuming you mean the method where every sub-story has to load an `.md` file.

Did you do this to get the nice syntax highlighting in the `.md` files?

I am not a fan of having that many of these files to be honest. It gets unwieldy quickly as each story file (`stories.js`) can contain multiple sub stories and each of these sub stories would then have to load the relevant `.md` files.

**Pull request closed without merging**
